import * as LucideIcons from 'lucide-react';

export const LucideIconConfig = {
  house: LucideIcons.House,
  bookmark: LucideIcons.Bookmark,
  settings: LucideIcons.Settings,
  user: LucideIcons.User,
  file: LucideIcons.File,
  folder: LucideIcons.Folder,
  mail: LucideIcons.Mail,
  messageSquare: LucideIcons.MessageSquare,
  search: LucideIcons.Search,
  heart: LucideIcons.Heart,
  star: LucideIcons.Star,
  shoppingCart: LucideIcons.ShoppingCart,
  image: LucideIcons.Image,
  video: LucideIcons.Video,
  music: LucideIcons.Music,
  gamepad2: LucideIcons.Gamepad2,
  code: LucideIcons.Code,
  database: LucideIcons.Database,
  cloud: LucideIcons.Cloud,
  download: LucideIcons.Download,
  upload: LucideIcons.Upload,
  link: LucideIcons.Link,
  map: LucideIcons.Map,
  calendar: LucideIcons.Calendar,
  clock: LucideIcons.Clock,
  wrench: LucideIcons.Wrench,
  package: LucideIcons.Package,
  coffee: LucideIcons.Coffee,
  pizza: LucideIcons.Pizza,
  rocket: LucideIcons.Rocket,
  bell: LucideIcons.Bell,
  book: LucideIcons.Book,
  bookOpen: LucideIcons.BookOpen,
  bookMarked: LucideIcons.BookMarked,
};